from pydantic import BaseModel, Field
from typing import List, Optional


class RecruiterRequest(BaseModel):
    """
    Request received from the recruiter.
    """

    goal: str = Field(
        ...,
        description="Natural language hiring goal provided by the recruiter."
    )


class ExecutionStep(BaseModel):
    """
    Represents one action in the hiring workflow.
    """

    step_number: int
    title: str
    description: str


class RecruiterPlan(BaseModel):
    """
    Structured execution plan generated by the Chief Recruiter.
    """

    hiring_goal: str

    summary: str

    execution_plan: List[ExecutionStep]

    clarification_questions: List[str] = []

    requires_human_approval: bool = True


class RecruiterResponse(BaseModel):
    """
    Final response returned to frontend.
    """

    status: str

    message: str

    plan: RecruiterPlan